#pragma once
#include <openssl/core_dispatch.h>

OSSL_FUNC_signature_newctx_fn GsSignatureNewCtx;
OSSL_FUNC_signature_freectx_fn GsSignatureFreeCtx;
OSSL_FUNC_signature_dupctx_fn GsSignatureDupCtx;

OSSL_FUNC_signature_sign_init_fn GsSignatureSignVerifyInit;
OSSL_FUNC_signature_sign_fn GsSignatureSign;

//OSSL_FUNC_signature_verify_init_fn GsSignatureVerifyInit;
OSSL_FUNC_signature_verify_fn GsSignatureVerify;

OSSL_FUNC_signature_digest_sign_init_fn GsSignatureDigestSignVerifyInit;
//OSSL_FUNC_signature_digest_verify_init_fn GsSignatureDigestSignVerifyInit;
OSSL_FUNC_signature_digest_sign_update_fn GsSignatureDigestSignVerifyUpdate;
//OSSL_FUNC_signature_digest_verify_update_fn GsSignatureDigestSignVerifyUpdate;
OSSL_FUNC_signature_digest_sign_final_fn GsSignatureDigestSignFinal;
OSSL_FUNC_signature_digest_verify_final_fn GsSignatureDigestVerifyFinal;

OSSL_FUNC_signature_get_ctx_params_fn GsSignatureGetCtxParams;
OSSL_FUNC_signature_gettable_ctx_params_fn GsSignatureGettableCtxParams;
OSSL_FUNC_signature_get_ctx_md_params_fn GsSignatureGetCtxMdParams;
OSSL_FUNC_signature_gettable_ctx_md_params_fn GsSignatureGettableCtxMdParams;
OSSL_FUNC_signature_set_ctx_params_fn GsSignatureSetCtxParams;
OSSL_FUNC_signature_settable_ctx_params_fn GsSignatureSettableCtxParams;
OSSL_FUNC_signature_set_ctx_md_params_fn GsSignatureSetCtxMdParams;
OSSL_FUNC_signature_settable_ctx_md_params_fn GsSignatureSettableCtxMdParams;
