#include <openssl/asn1t.h>
#include <openssl/ossl_typ.h>
#include <openssl/x509.h>
#include "asn1_params.h"

ASN1_NDEF_SEQUENCE( GOST_KEY_INFO ) =
{
    ASN1_SIMPLE( GOST_KEY_INFO, wrappedKey, ASN1_OCTET_STRING ),
    ASN1_SIMPLE( GOST_KEY_INFO, wrappedKeyMac, ASN1_OCTET_STRING )
}
ASN1_NDEF_SEQUENCE_END( GOST_KEY_INFO )
IMPLEMENT_ASN1_FUNCTIONS( GOST_KEY_INFO )

ASN1_NDEF_SEQUENCE( GOST_KEY_AGREEMENT_INFO ) =
{
    ASN1_SIMPLE( GOST_KEY_AGREEMENT_INFO, cipher, ASN1_OBJECT ),
    ASN1_IMP_OPT( GOST_KEY_AGREEMENT_INFO, ephemeralKey, X509_PUBKEY, 0 ),
    ASN1_SIMPLE( GOST_KEY_AGREEMENT_INFO, iv, ASN1_OCTET_STRING )
}
ASN1_NDEF_SEQUENCE_END( GOST_KEY_AGREEMENT_INFO )
IMPLEMENT_ASN1_FUNCTIONS( GOST_KEY_AGREEMENT_INFO )

ASN1_NDEF_SEQUENCE( GOST_KEY_TRANSPORT ) =
{
    ASN1_SIMPLE( GOST_KEY_TRANSPORT, keyInfo, GOST_KEY_INFO ),
    ASN1_IMP( GOST_KEY_TRANSPORT, keyAgreeInfo,
              GOST_KEY_AGREEMENT_INFO, 0 )
}
ASN1_NDEF_SEQUENCE_END( GOST_KEY_TRANSPORT )
IMPLEMENT_ASN1_FUNCTIONS( GOST_KEY_TRANSPORT )

ASN1_NDEF_SEQUENCE( PSKeyTransport_gost ) =
{
    ASN1_SIMPLE( PSKeyTransport_gost, psexp, ASN1_OCTET_STRING ),
    ASN1_SIMPLE( PSKeyTransport_gost, ephemeralKey, X509_PUBKEY )
}
ASN1_NDEF_SEQUENCE_END(PSKeyTransport_gost)
IMPLEMENT_ASN1_FUNCTIONS(PSKeyTransport_gost)


ASN1_NDEF_SEQUENCE( GostKeyParams ) =
{
    ASN1_SIMPLE( GostKeyParams, keyParams, ASN1_OBJECT ),
    ASN1_OPT( GostKeyParams, hashParams, ASN1_OBJECT ),
    ASN1_OPT( GostKeyParams, cipherParams, ASN1_OBJECT ),
}
ASN1_NDEF_SEQUENCE_END( GostKeyParams )
IMPLEMENT_ASN1_FUNCTIONS( GostKeyParams )
IMPLEMENT_PEM_rw( GostKeyParams, GostKeyParams, "GOST KEY PARAMS", GostKeyParams )

ASN1_NDEF_SEQUENCE( GOST89_PARAMS ) =
{
    ASN1_SIMPLE( GOST89_PARAMS, iv, ASN1_OCTET_STRING ),
    ASN1_SIMPLE( GOST89_PARAMS, sbox, ASN1_OBJECT ),
}
ASN1_NDEF_SEQUENCE_END( GOST89_PARAMS )
IMPLEMENT_ASN1_FUNCTIONS( GOST89_PARAMS )

ASN1_NDEF_SEQUENCE( GOST_CLIENT_KEY_EXCHANGE ) =
{
    ASN1_SIMPLE( GOST_CLIENT_KEY_EXCHANGE, gkt, GOST_KEY_TRANSPORT )
}
ASN1_NDEF_SEQUENCE_END( GOST_CLIENT_KEY_EXCHANGE )
IMPLEMENT_ASN1_FUNCTIONS( GOST_CLIENT_KEY_EXCHANGE )

ASN1_NDEF_SEQUENCE( GOST_MASKED_KEY ) =
{
    ASN1_SIMPLE( GOST_MASKED_KEY, maskedPrivateKey, ASN1_OCTET_STRING ),
    ASN1_SIMPLE( GOST_MASKED_KEY, publicKey, ASN1_OCTET_STRING )
}
ASN1_NDEF_SEQUENCE_END( GOST_MASKED_KEY )
IMPLEMENT_ASN1_FUNCTIONS( GOST_MASKED_KEY )

