if (ENABLE_TESTS)
    enable_testing()
endif (ENABLE_TESTS)

if (ENABLE_CODE_COVERAGE)
    include(CodeCoverage)
    append_coverage_compiler_flags()
endif (ENABLE_CODE_COVERAGE)

if (ENABLE_ADDRESS_SANITIZER)
    set(ASAN_CXX_FLAGS -fsanitize=address)
    set(ASAN_LINKER_FLAGS -fsanitize=address)
    set(CMAKE_REQUIRED_FLAGS "${ASAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${ASAN_CXX_FLAGS}" HAVE_ADDRESS_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_ADDRESS_SANITIZER)
        add_compile_options(${ASAN_CXX_FLAGS})
        add_link_options(${ASAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the address sanitizer!")
    endif ()
endif (ENABLE_ADDRESS_SANITIZER)

if (ENABLE_THREAD_SANITIZER)
    set(TSAN_CXX_FLAGS -fsanitize=thread)
    set(TSAN_LINKER_FLAGS -fsanitize=thread)
    set(CMAKE_REQUIRED_FLAGS "${TSAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${TSAN_CXX_FLAGS}" HAVE_THREAD_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_THREAD_SANITIZER)
        add_compile_options(${TSAN_CXX_FLAGS})
        add_link_options(${TSAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the thread sanitizer!")
    endif ()
endif (ENABLE_THREAD_SANITIZER)

if (ENABLE_UB_SANITIZER)
    set(UBSAN_CXX_FLAGS -fsanitize=undefined -fno-sanitize=alignment)
    set(UBSAN_LINKER_FLAGS -fsanitize=undefined -fno-sanitize=alignment)
    set(CMAKE_REQUIRED_FLAGS "${UBSAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${UBSAN_CXX_FLAGS}" HAVE_UB_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_UB_SANITIZER)
        add_compile_options(${UBSAN_CXX_FLAGS})
        add_link_options(${UBSAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the undefined behavior sanitizer!")
    endif ()
endif (ENABLE_UB_SANITIZER)

